import 'package:russianalphabet/model/letter_card_item.dart';

import 'letters.dart';

final List<LetterCardItem> letterCardItems = [
  LetterCardItem(key: a.key, text: a.letter),
  LetterCardItem(key: b.key, text: b.letter),
  LetterCardItem(key: v.key, text: v.letter),
  LetterCardItem(key: g.key, text: g.letter),
  LetterCardItem(key: d.key, text: d.letter),
  LetterCardItem(key: ye.key, text: ye.letter),
  LetterCardItem(key: yo.key, text: yo.letter),
  LetterCardItem(key: zh.key, text: zh.letter),
  LetterCardItem(key: z.key, text: z.letter),
  LetterCardItem(key: i.key, text: i.letter),
  LetterCardItem(key: j.key, text: j.letter),
  LetterCardItem(key: k.key, text: k.letter),
  LetterCardItem(key: l.key, text: l.letter),
  LetterCardItem(key: m.key, text: m.letter),
  LetterCardItem(key: n.key, text: n.letter),
  LetterCardItem(key: o.key, text: o.letter),
  LetterCardItem(key: p.key, text: p.letter),
  LetterCardItem(key: r.key, text: r.letter),
  LetterCardItem(key: s.key, text: s.letter),
  LetterCardItem(key: t.key, text: t.letter),
  LetterCardItem(key: u.key, text: u.letter),
  LetterCardItem(key: f.key, text: f.letter),
  LetterCardItem(key: kh.key, text: kh.letter),
  LetterCardItem(key: c.key, text: c.letter),
  LetterCardItem(key: ch.key, text: ch.letter),
  LetterCardItem(key: sh.key, text: sh.letter),
  LetterCardItem(key: shch.key, text: shch.letter),
  LetterCardItem(key: hard.key, text: hard.letter),
  LetterCardItem(key: y.key, text: y.letter),
  LetterCardItem(key: soft.key, text: soft.letter),
  LetterCardItem(key: EMPTY_LETTER.key, text: EMPTY_LETTER.letter),
  LetterCardItem(key: eh.key, text: eh.letter),
  LetterCardItem(key: yu.key, text: yu.letter),
  LetterCardItem(key: ya.key, text: ya.letter),
  LetterCardItem(key: EMPTY_LETTER.key, text: EMPTY_LETTER.letter),
];
